#!/bin/bash
LOG_PREFIX="$(dirname $0)/logs/l_"

KEY=""
VALUE=""

while getopts ":c:s:z:k:o:" opt; do
	case $opt in
		k)
			KEY="$OPTARG"
			;;
		o)
			VALUE="$OPTARG"
			;;
		*)
			;;
	esac
done

if [ "$KEY" != "error_key" ]; then
	echo -n "$VALUE" > "${LOG_PREFIX}${KEY}"
	echo -e "info from server: \"Processed 1 Failed 0 Total 1 Seconds spent 0.0\"\nsent: 1; skipped: 0; total: 1\n"
else
	echo -e "info from server: \"Processed 0 Failed 1 Total 1 Seconds spent 0.0\"\nsent: 1; skipped: 0; total: 1\n"
fi

